### ISSUE TITLE
DEBUG mode seem to be not working on Docker

### ISSUE THREAD

**Issue by llaumgui** [fligneul/aps2mqtt#11]
Hi,

I use docker and would like to enable debuging (because scheduler seem not working). But the DEBUG env variable have no effect.

**Comment by fligneul** [comment]
Hi,

Thanks for your test, I will have a look

**Comment by llaumgui** [comment]
Thanks to you !

For information, I try true / True / 1, not working. But I can't find the relation between env variable and log level in code. I thinks it's that the issue.

**Comment by fligneul** [comment]
Hi,
There was a mistake in the documentation for the DEBUG value, it should be "True" and not "true".
To be more safe, I reworked the boolean parsing to be more reliable.

The new version is released (1.1.3), can you test it again?
