### ISSUE TITLE
No update on docker

### ISSUE THREAD

**Issue by llaumgui** [fligneul/aps2mqtt#16]
Hi,

thanks for fix #11. Now I can see full trace now. The issue is that on Docker I have an update on start but not update after.

~~~
2023-12-05T07:56:20.966375344Z INFO:aps2mqtt.main:Update finished, next update at: 2023-12-05 08:59:46
~~~

For information, I start my container with `TZ: Europe/Paris` environment variable.

Is it normal `07:56:20.966375344Z` VS `2023-12-05 08:59:46` ?

**Comment by fligneul** [comment]
Can you share your whole container config (without your private informations) ?
It looks like there is a timezone error, I will investigate

**Comment by llaumgui** [comment]
Hi,


```docker-compose
version: '3'

services:
  aps2mqtt:
    image: fligneul/aps2mqtt:latest
    container_name: aps2mqtt
    environment:
      TZ: Europe/Paris
      DEBUG: True
      APS_ECU_IP: 192.168.X.XX
      APS_ECU_POSITION_LAT: XX.XXXXXXX
      APS_ECU_POSITION_LNG: X.XXXXXX
      MQTT_BROKER_HOST: mqtt2_mosquitto
      MQTT_BROKER_USER: jeedom
      MQTT_BROKER_PASSWD: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```
